[app]
platformio_cmd = platformio
cubemx_cmd = C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeMX/STM32CubeMX.exe
java_cmd = C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeMX/jre/bin/java.exe

[project]
cubemx_script_content = config load ${ioc_file_absolute_path}
	generate code ${project_dir_absolute_path}
	exit
platformio_ini_patch_content = [platformio]
	include_dir = Inc
	src_dir = Src
board = stm32f103c8
ioc_file = segera pio.ioc
cleanup_ignore = segera pio.ioc
cleanup_use_git = False
inspect_ioc = True
last_error = FileNotFoundError: [WinError 2] Не удается найти указанный файл
	Traceback (most recent call last):
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\site-packages\stm32pio\cli\app.py", line 199, in main
	    project.pio_init()
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\site-packages\stm32pio\core\project.py", line 137, in pio_init
	    return self.platformio.init(board=self.config.get('project', 'board'))
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\site-packages\stm32pio\core\pio.py", line 176, in init
	    process = subprocess.run(command_arr, encoding='utf-8', stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
	    with Popen(*popenargs, **kwargs) as process:
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "C:\Users\georg\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
	    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

